apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - name: pod1
    args:
    - /app/server
    - liveness_dep
    image: hongminhcbg/base-image:v0.0.3
    resources: {}
    env:
    - name: HEALTH_DEPENDENCY
      valueFrom:
        configMapKeyRef:
          name: pod1
          key: HEALTH_DEPENDENCY 
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
