apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod1
  name: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod1
    spec:
      containers:
      - command:
        - /app/server
        - liveness_dep
        image: hongminhcbg/base-image:v0.0.4
        name: base-image
        resources: {}
        env:
        - name: HEALTH_DEPENDENCY
          valueFrom:
            configMapKeyRef:
              name: pod1
              key: HEALTH_DEPENDENCY 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
status: {}
