apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pod2-svc
  name: pod2-svc
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pod2
  type: NodePort
status:
  loadBalancer: {}
