apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod2
  name: pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod2
    spec:
      containers:
      - command:
        - /app/server
        - liveness_dep
        image: hongminhcbg/base-image:v0.0.4
        name: pod2 
        resources: {}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
status: {}
