apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: redis
spec:
  containers:
  - image: redis
    name: pod1
    resources: {}
    volumeMounts:
    - name: pod1-pvc
      mountPath: '/data'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: pod1-pvc
      persistentVolumeClaim:
        claimName: pvc-mint
status: {}
