apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mint  
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100M
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
