apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: elasticsearch
    tier: node
  name: elasticsearch
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - image: egistry.k8s.io/fluentd-elasticsearch:1.20 
        imagePullPolicy: IfNotPresent
        name: elasticsearch 
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
